# Generated by Django 3.2.9 on 2021-12-11 11:47

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='Slog(검색을위한)')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='Slog(검색을위한)')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='이름')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='Slog(검색을위한)')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='휴대폰')),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='기타번호')),
                ('image', models.ImageField(blank=True, upload_to='client/%Y/%m/%d')),
                ('personal_number', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='주민등록번호')),
                ('business_number', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='사업자번호')),
                ('crprt_rgnmb', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='법인등록번호')),
                ('bank', models.CharField(max_length=200, verbose_name='결제은행')),
                ('bank_number', models.CharField(max_length=200, verbose_name='계좌번호')),
                ('address', models.CharField(max_length=250, verbose_name='주소')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('meta_description', models.TextField(blank=True)),
                ('available_display', models.BooleanField(default=True, verbose_name='Display')),
                ('available_order', models.BooleanField(default=True, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('companyname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companynames', to='client.companyname', verbose_name='소속회사')),
                ('expertise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='client.expertise', verbose_name='구분')),
            ],
        ),
    ]
