# Generated by Django 3.2.9 on 2021-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결제은행'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bank_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='계좌번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='crprt_rgnmb',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='법인등록번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='팩스번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='주민등록번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='휴대폰'),
        ),
    ]
