# Generated by Django 3.2.9 on 2021-12-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20211211_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_number',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='사업자번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='crprt_rgnmb',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='법인등록번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fax_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='팩스번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='client',
            name='personal_number',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True, verbose_name='주민등록번호'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='휴대폰'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='Slog(검색을위한)'),
        ),
    ]
